package cl.security.qaAutomation.flow;

import org.junit.BeforeClass;
import org.junit.runners.Suite.SuiteClasses;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import cl.security.qaAutomation.stageSet.NuevaPropuestaHombreStageSet;
import cl.security.qaAutomation.stageSet.NuevaPropuestaMujerStageSet;
import cl.security.qaAutomation.stageSet.TC10StageSet;
import cl.security.qaAutomation.stageSet.TC11StageSet;
import cl.security.qaAutomation.stageSet.TC12StageSet;
import cl.security.qaAutomation.stageSet.TC13StageSet;
import cl.security.qaAutomation.stageSet.TC14StageSet;
import cl.security.qaAutomation.stageSet.TC15StageSet;
import cl.security.qaAutomation.stageSet.TC16StageSet;
import cl.security.qaAutomation.stageSet.TC17StageSet;
import cl.security.qaAutomation.stageSet.TC18StageSet;
import cl.security.qaAutomation.stageSet.TC19StageSet;
import cl.security.qaAutomation.stageSet.TC1StageSet;
import cl.security.qaAutomation.stageSet.TC20StageSet;
import cl.security.qaAutomation.stageSet.TC21StageSet;
import cl.security.qaAutomation.stageSet.TC22StageSet;
import cl.security.qaAutomation.stageSet.TC23StageSet;
import cl.security.qaAutomation.stageSet.TC24StageSet;
import cl.security.qaAutomation.stageSet.TC25StageSet;
import cl.security.qaAutomation.stageSet.TC26StageSet;
import cl.security.qaAutomation.stageSet.TC27StageSet;
import cl.security.qaAutomation.stageSet.TC28StageSet;
import cl.security.qaAutomation.stageSet.TC29StageSet;
import cl.security.qaAutomation.stageSet.TC2StageSet;
import cl.security.qaAutomation.stageSet.TC30StageSet;
import cl.security.qaAutomation.stageSet.TC31StageSet;
import cl.security.qaAutomation.stageSet.TC32StageSet;
import cl.security.qaAutomation.stageSet.TC33StageSet;
import cl.security.qaAutomation.stageSet.TC34StageSet;
import cl.security.qaAutomation.stageSet.TC35StageSet;
import cl.security.qaAutomation.stageSet.TC36StageSet;
import cl.security.qaAutomation.stageSet.TC37StageSet;
import cl.security.qaAutomation.stageSet.TC38StageSet;
import cl.security.qaAutomation.stageSet.TC39StageSet;
import cl.security.qaAutomation.stageSet.TC3StageSet;
import cl.security.qaAutomation.stageSet.TC40StageSet;
import cl.security.qaAutomation.stageSet.TC41StageSet;
import cl.security.qaAutomation.stageSet.TC42StageSet;
import cl.security.qaAutomation.stageSet.TC43StageSet;
import cl.security.qaAutomation.stageSet.TC49StageSet;
import cl.security.qaAutomation.stageSet.TC4StageSet;
import cl.security.qaAutomation.stageSet.TC50StageSet;
import cl.security.qaAutomation.stageSet.TC51StageSet;
import cl.security.qaAutomation.stageSet.TC52StageSet;
import cl.security.qaAutomation.stageSet.TC53StageSet;
import cl.security.qaAutomation.stageSet.TC54StageSet;
import cl.security.qaAutomation.stageSet.TC55StageSet;
import cl.security.qaAutomation.stageSet.TC56StageSet;
import cl.security.qaAutomation.stageSet.TC57StageSet;
import cl.security.qaAutomation.stageSet.TC58StageSet;
import cl.security.qaAutomation.stageSet.TC59StageSet;
import cl.security.qaAutomation.stageSet.TC5StageSet;
import cl.security.qaAutomation.stageSet.TC60StageSet;
import cl.security.qaAutomation.stageSet.TC61StageSet;
import cl.security.qaAutomation.stageSet.TC62StageSet;
import cl.security.qaAutomation.stageSet.TC63StageSet;
import cl.security.qaAutomation.stageSet.TC64StageSet;
import cl.security.qaAutomation.stageSet.TC65StageSet;
import cl.security.qaAutomation.stageSet.TC66StageSet;
import cl.security.qaAutomation.stageSet.TC67StageSet;
import cl.security.qaAutomation.stageSet.TC68StageSet;
import cl.security.qaAutomation.stageSet.TC69StageSet;
import cl.security.qaAutomation.stageSet.TC6StageSet;
import cl.security.qaAutomation.stageSet.TC70StageSet;
import cl.security.qaAutomation.stageSet.TC71StageSet;
import cl.security.qaAutomation.stageSet.TC72StageSet;
import cl.security.qaAutomation.stageSet.TC73StageSet;
import cl.security.qaAutomation.stageSet.TC74StageSet;
import cl.security.qaAutomation.stageSet.TC75StageSet;
import cl.security.qaAutomation.stageSet.TC76StageSet;
import cl.security.qaAutomation.stageSet.TC77StageSet;
import cl.security.qaAutomation.stageSet.TC78StageSet;
import cl.security.qaAutomation.stageSet.TC79StageSet;
import cl.security.qaAutomation.stageSet.TC7StageSet;
import cl.security.qaAutomation.stageSet.TC80StageSet;
import cl.security.qaAutomation.stageSet.TC81StageSet;
import cl.security.qaAutomation.stageSet.TC82StageSet;
import cl.security.qaAutomation.stageSet.TC83StageSet;
import cl.security.qaAutomation.stageSet.TC84StageSet;
import cl.security.qaAutomation.stageSet.TC85StageSet;
import cl.security.qaAutomation.stageSet.TC86StageSet;
import cl.security.qaAutomation.stageSet.TC87StageSet;
import cl.security.qaAutomation.stageSet.TC88StageSet;
import cl.security.qaAutomation.stageSet.TC89StageSet;
import cl.security.qaAutomation.stageSet.TC8StageSet;
import cl.security.qaAutomation.stageSet.TC90StageSet;
import cl.security.qaAutomation.stageSet.TC91StageSet;
import cl.security.qaAutomation.stageSet.TC92StageSet;
import cl.security.qaAutomation.stageSet.TC93StageSet;
import cl.security.qaAutomation.stageSet.TC94StageSet;
import cl.security.qaAutomation.stageSet.TC95StageSet;
import cl.security.qaAutomation.stageSet.TC96StageSet;
import cl.security.qaAutomation.stageSet.TC97StageSet;

@SuiteClasses({
	NuevaPropuestaHombreStageSet.class,TC1StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC2StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC3StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC4StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC5StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC6StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC7StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC8StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC10StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC11StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC12StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC13StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC14StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC15StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC16StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC17StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC18StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC19StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC20StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC21StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC22StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC23StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC24StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC25StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC26StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC27StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC28StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC29StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC30StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC31StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC32StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC33StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC34StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC35StageSet.class, //OK
	NuevaPropuestaMujerStageSet.class,TC36StageSet.class,  //OK
	NuevaPropuestaHombreStageSet.class,TC37StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC38StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC39StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC40StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC41StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC42StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC43StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC49StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC50StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC51StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC52StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC53StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC54StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC55StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC56StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC57StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC58StageSet.class, //OK 
	NuevaPropuestaHombreStageSet.class,TC59StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC60StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC61StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC62StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC63StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC64StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC65StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC66StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC67StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC68StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC69StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC70StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC71StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC72StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC73StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC74StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC75StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC76StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC77StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC78StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC79StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC80StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC81StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC82StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC83StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC84StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC85StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC86StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC87StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC88StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC89StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC90StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC91StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC92StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC93StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC94StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC95StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC96StageSet.class, //OK
	NuevaPropuestaHombreStageSet.class,TC97StageSet.class, //OK
	
})

public class CompassTest extends BaseFlow{
	private static final Logger LOGGER = LoggerFactory.getLogger(CompassTest.class);
    @BeforeClass
    public static void flag() throws Exception {
    	LOGGER.info("**************************************");
        LOGGER.info("*  Ejecutando flujo de Compass DPS   *");
        LOGGER.info("**************************************");
    }
}
